### PR TITLE
allow main thread to sleep

### PR DESCRIPTION
**Pull request by sam-kirby**
Significant performance improvement

### CODE REVIEW

**Comment by lewis-weinberger** [comment]
This is great! :+1: 

One slight issue now is the introduction of some visual input lag for the cursor. The cursor is displayed by the main thread, but as input is read asynchronously by another thread, if you move it across the screen quite fast then there can be a delay before the position is updated on the map. Of course setting a smaller tick time solves this, but eventually you approach the original (under-performant) game rate, and also the speed of the crabs is now tied to the tick rate (so they end up going too fast!). 

Perhaps we can figure out an optimum (and machine-dependent?) tick rate to replace the default.

**Comment by sam-kirby** [comment]
Perhaps you could just process more than one input from the stdin iterator per loop? Haven't tested but something like
```rust
loop {
  let key = stdin.next().unwrap();
  match key {
    Some(key) => {
      // do stuff
    }
    None => { break;}
  }
}
```

**Comment by sam-kirby** [comment]
Although next returns an Option<Result<Key, Error>> so that's slightly backwards right now.

**Comment by sam-kirby** [comment]
There'll still be lag, but every input a player makes between ticks will be processed on the next tick.

**Comment by lewis-weinberger** [comment]
Yeah that could work! Using the current code I guess it would just simply be:

```rust
loop {
    stdin.next().and_then(|res| {
    res.ok()
     .map(|key| user_input(key, &mut user, &mut complete, &mut reset, &mut map))
    });
}
```

**Comment by sam-kirby** [comment]
I might be missing something, but how do you break out of that loop?

**Comment by lewis-weinberger** [comment]
Whoops er... maybe something like:

```rust
let mut input = true;
while input {
    let next = stdin.next().and_then(|res| {
        res.ok()
        .map(|key| user_input(key, &mut user, &mut complete, &mut reset, &mut map))
    });
    input =  next.is_none();
}
```
Will need to run it to see if that last line actually works! Anyway I agree with looping over all the queue from the other thread in one go.

**Comment by sam-kirby** [comment]
```rust
            loop {
                match stdin.next() {
                    Some(res) => {
                        res.ok().map(|key| {
                            user_input(key, &mut user, &mut complete, &mut reset, &mut map);
                        });
                    }
                    None => { break; }
                }
            }
```
is my current favourite syntax as it's clear and doesn't require any extra local variables. But both work and it's your code so take your pick :smile:

**Comment by sam-kirby** [comment]
Actually your version seems to end up blocking the UI update until a key is pressed.

**Comment by lewis-weinberger** [comment]
> ```rust
>             loop {
>                 match stdin.next() {
>                     Some(res) => {
>                         res.ok().map(|key| {
>                             user_input(key, &mut user, &mut complete, &mut reset, &mut map);
>                         });
>                     }
>                     None => { break; }
>                 }
>             }
> ```
> 
> is my current favourite syntax as it's clear and doesn't require any extra local variables. But both work and it's your code so take your pick 😄

Yeah that works, and I agree the syntax is bit cleaner!

**Pull request merged**
